### ISSUE TITLE
How to start connector? 

### ISSUE THREAD

**Issue by ColaFantaSprite** [cobwebch/svconnector#17]
Hello,

I'm pretty new to svconnector, but I did not find a way to start it. I have to get a JSON from an external url and place it on my webspace once a day to get the updated content. I guess I can do this with the svconnector and/or the Typo3 scheduler.

In the backend I only found the connector test. I tried it for the JSON connector and it has shown me the correct content. But how can I get the connector started? Where I habe to configure it?

Thanks

**Comment by fsuter** [comment]
Hi.

The connector classes are all services and can be instantiated with the following code:
`
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceService('connector', 'json');
`
The second argument depends on which connector you want. In your case it is "json".

**Comment by ColaFantaSprite** [comment]
Hi, thanks for your answer! Can you Tell me where I have to put the in, is it in TypoScript? Never worked with Services before :S

**Comment by fsuter** [comment]
That's PHP code. So you have to put it somewhere in a class, probably as part of a custom extension of your own. I realise that my example was probably not complete enough. What you need to do is:
```php
$connector = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceService('connector', 'json');
$json = $connector->fetchRaw(['uri' => 'URI of your JSON source']);
```
With this you get your JSON input as a string in the `$json` variable.
You can also get a PHP array directly by calling:
```php
$connector = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceService('connector', 'json');
$json = $connector->fetchArray(['uri' => 'URI of your JSON source']);
```
In this case, variable `$json` contains an array correspoding to the structure of the JSON data.
I hope this helps you get further.

**Comment by ColaFantaSprite** [comment]
Sorry, to be honest I feel really dumb right now. So that means that I have to create a custom extension first somehow?

I want to get the json from an external url to my webspace, because the direct access to the external json is allowed due to CORS. I thought I could get the external json with svconnector_json to my webspace and configure a cron job to do this daily.

**Comment by fsuter** [comment]
Well, it is PHP code, so you need to put it somewhere in a class. This can be as simple as a USER function which you call via TypoScript.

If you want to somehow import your data, you may want to us my other extension "External Import", which relies on connector services to import data into an existing or custom database table. External import comes with a Scheduler task. However this is more effort as you then need to program the display of the imported data. In such a scenario you would start by creating an Extbase extension as if the data was in your TYPO3 database. Then you use External Import to map the external data to the TYPO3 table.

Maybe all this is a bit too complicated for your needs. It is also possible to allow CORS. I'm not a specialist, but there are pages on this topic such as: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Another possibility, if you are familiar with the "eID" mechanisms from TYPO3, you could program such a simple class, use the Connector service inside it, and call this "eID" request with AJAX. This would give you the same result as the direct call, but the call would remain local.

I hope this helps.

**Comment by fsuter** [comment]
I hope that you solved your problem. I'm closing this issue. Feel free to open it again if needed.
