### ISSUE TITLE
Be aware of 'services API' deprecation in core v10

### ISSUE THREAD

**Issue by lolli42** [cobwebch/svconnector#23]
Hey Francois. Good to see you.

We stumbled upon the extension when searching for usages of TYPO3\CMS\Core\Service\AbstractService, which we'll deprecate with https://review.typo3.org/c/Packages/TYPO3.CMS/+/69461 - the entire 'services API' with GeneralUtility::makeInstanceService() plus the related ExtensionManagementUtility methods is pretty clumsy and we'll further slim-down / streamline this in core.

So, this issue is just a warning that you may want to take some action for your extension, probably my moving away from the core services API and adding something (more simple?) on your own.

**Comment by fsuter** [comment]
Hi Christian. Good to see you too.

Thanks for the heads up. I guess I'll introduce some factory pattern in such a case.
