### ISSUE TITLE
Missing php version requirement

### ISSUE THREAD

**Issue by FireLizard** [cobwebch/svconnector#6]
Hello,

since v3.2.0 [this line of code](https://github.com/cobwebch/svconnector/commit/574c46101801add85943d18fa144f5eae19e3292#diff-e604ce900d1431cc5cfc262220f0391dR125) require a php version >= 7.1 ([void_return_type](https://wiki.php.net/rfc/void_return_type)).

Now when resolving my dependencies using composer, no error is thrown on my php 7.0 machine in cause of the missing require-statement in your _composer.json_.

Can you add the `"php": "^7.1"` requirement please?

Thanks in advance :)

**Comment by EvilBMP** [comment]
+1 - that's really annoying - because TYPO3 7.6 officially supports PHP 7.0 (which most LTS systems serve).

Please remove the type declarations for return types in the FileUtility - no other class in svconnector is using this new format. Thanks.

**Comment by fsuter** [comment]
Sorry about this. Resolved with 664e39eb7cf9881adab6f8c6add171c6b8582bee. Will do a hotfix release today or tomorrow.
