### ISSUE TITLE
FileUtility does not allow the import of local files because of default headers.

### ISSUE THREAD

**Issue by EvilBMP** [cobwebch/svconnector#8]
Thanks for fixing #6 - but the FileUtility still has an issue regarding importing local files. 

In the main `else` branch of the `getFileContent()` method is a check for a fully qualified uri and if the uri is not a fully qualified uri the `$finalUri` will be retrieved using `GeneralUtility::getFileAbsFileName($uri)`. 
In this `else` branch the `$headers` variable must be set to `false`, otherwise the later call of `GeneralUtility::getUrl()` will throw the error _"Reading headers is not allowed for this protocol."_

```php
            if (preg_match('/^(?:http|ftp)s?|s(?:ftp|cp):/', $uri)) {
                $finalUri = $uri;
            } else {
                // This will resolve "EXT:" syntax, resolve paths relative to the TYPO3 root
                // and preserve absolute paths that are allowed by the TYPO3 configuration.
                $finalUri = GeneralUtility::getFileAbsFileName($uri);
                $headers = false;
            }
```

I hope the description is clear, I don't want to make a pull request for this single line. Thanks.

**Comment by fsuter** [comment]
I can't reproduce the behaviour on my machine, but I'll take your word for granted. Anyway headers should not be necessary for reading local files.

Actually `GeneralUtility::getUrl()` expects `null` as a default value when no headers are defined. I'm thinking that it might be cleaner to change the declaration of the `getFileContent()` method to:

```
    /**
     * Reads data from a file pointed to by a versatile URI.
     *
     * The URI cannot only be the usual fully-qualified URI, but also use a syntax to trigger reading from the FAL
     * (FAL:storage_uid:file_identifier) or start with a special key pointing to a dedicated file reader
     * (declared as a hook).
     *
     * @param string $uri Address of the file to read
     * @param array|null $headers Headers to pass on to the request
     * @return string|bool
     */
    public function getFileContent($uri, $headers = null)
    {
```

Could you test if that solves your issue? It seems like a cleaner solution to me.

**Comment by EvilBMP** [comment]
Sorry, for the late reply. That would be of course a cleaner solution. 

But right now it's not working as expected because you call the `FileUtility->getFileContent()` from the `ConnectorFeed` service class with an (empty) array - see line ~153 and before.

**Comment by EvilBMP** [comment]
> Actually GeneralUtility::getUrl() expects null as a default value when no headers are defined. 

FYI: That's not the case in v7.6. Just looked in the API ... The default value was changed to `null` in v8

https://api.typo3.org/typo3cms/7/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_general_utility.html#ae1e248cb7ee687542a49328d24591de6

But that shouldn't matter though since neither `false` nor `null` fulfil the `is_array()` check in getUrl(). But you need to change the default initialization of the `$headers` variable in the `ConnectorFeed` service.

**Comment by EvilBMP** [comment]
Any progress here? Sorry for beeing annoying, but I don't want to deploy my branch(es) ;-)

**Comment by fsuter** [comment]
It looks all good but I need time to prepare the releases. Currently it's school holidays here, so I'm more busy than usual ;-)

I'll try to settle that by the end of the week.
